#!/bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24

CLK_ICON=$(echo -e '\ue017')
BATT_ICON=$(echo -e '\ue037')
VOL_ICON=$(echo -e '\ue05d')
WIFI_ICON=$(echo -e '\ue0f0')

clock() {
    DATE=$(date "+%d/%m/%y ${CLK_ICON} %H:%M")
    echo "C${DATE}"
}

battery() {
    BAT1=$(acpi --battery | awk -F, '{print $2}' | head -1)
    BAT2=$(acpi --battery | awk -F, '{print $2}' | tail -1)
    echo  "B${BATT_ICON}${BAT1} ${BATT_ICON}${BAT2}"
}

volume() {
    VOL=$(amixer -c 0 sget Master | awk '$0~/%/{print $4}' | tr -d '[]%')
    echo "V${VOL_ICON} ${VOL}"
}

wifi_ssid() {
    if [[ -n $(iwgetid -r) ]]; then
        ESSID=$(iwgetid -r)
    else
        ESSID="null"
    fi

    echo "S${WIFI_ICON} ${ESSID}"
}

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

while :
do
    (
        echo $(clock)
        echo $(battery)
        echo $(volume)
        echo $(wifi_ssid)
    ) > "$PANEL_FIFO"
    sleep 1
done &

. ~/.config/bspwm/panel/panel_colors

cat "$PANEL_FIFO" | \
    ~/.config/bspwm/panel/panel_bar | \
    lemonbar \
    -g x$PANEL_HEIGHT \
    -f "-misc-stlarch-medium-r-normal-*-10-100-75-75-c-80-iso10646-1" \
    -f "-*-terminus-medium-r-normal-*-14-*-*-*-c-*-*-1" \
    -F "$COLOR_FOREGROUND" \
    -B "$COLOR_BACKGROUND" &

wait
