#!/bin/bash

bspc monitor -d $(echo -e '\uf269') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0c2')

bspc config border_width        0
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config click_to_focus      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Steam follow=off floating=on

~/.config/bspwm/panel/panel &
