#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Steam follow=no

~/.config/bspwm/panel/panel &
