#!/bin/bash

#Define the battery
Battery() {
    BATPERC=$(acpi --battery | awk -F, '{print $2}' | head -1)
    echo "$BATPERC"
}

# Print the percentage
while true; do
    echo "B$(Battery)"
    sleep 1;
done
